export const API_CONFIG = {
  BASE_URL: import.meta.env.MODE === 'production' 
    ? import.meta.env.VITE_API_URL 
    : import.meta.env.VITE_API_URL_DEV,
  TIMEOUT: 30000,
  
  VITE_EMAIL_JS_SERVICE_ID: import.meta.env.VITE_EMAIL_JS_SERVICE_ID,
  VITE_EMAIL_JS_TEMPLATE_CONTACT: import.meta.env.VITE_EMAIL_JS_TEMPLATE_CONTACT,
  VITE_EMAIL_JS_TEMPLATE_ORDER_CONFIRMATION: import.meta.env.VITE_EMAIL_JS_TEMPLATE_ORDER_CONFIRMATION,
  VITE_EMAIL_JS_TEMPLATE_ORDER_CONFIRMATION_ADMIN: import.meta.env.VITE_EMAIL_JS_TEMPLATE_ORDER_CONFIRMATION_ADMIN,
  VITE_EMAIL_JS_TEMPLATE_INQUIRY_RESPONSE: import.meta.env.VITE_EMAIL_JS_TEMPLATE_INQUIRY_RESPONSE,
  VITE_EMAIL_JS_PUBLIC_KEY: import.meta.env.VITE_EMAIL_JS_PUBLIC_KEY,
};

export const COLORS = {
  PRIMARY: '#494949',
  ACCENT: '#CA3836',
  SECONDARY: '#6AAFDB',
  GRAY_LIGHT: '#f9f9f9',
  GRAY_MEDIUM: '#ECECEC',
};